GET http://localhost:8080/actuator/health
Authorization: Basic merchant changeit


###
# @name Create Merchant
POST http://localhost:8080/merchant
Content-Type: application/json
Authorization: Basic merchant changeit
X-XSRF-TOKEN: ae9a0bda-5fe0-4d71-9a13-2d1b4fffc368

{
  "merchantName": "Merchant A",
  "email": "memail@a.com",
  "description": "Merchant A Description"
}

###
# @name Create Merchant full
POST http://localhost:8080/merchant
Content-Type: application/json
Authorization: Basic merchant changeit
X-XSRF-TOKEN: ae9a0bda-5fe0-4d71-9a13-2d1b4fffc368

{
  "id": 44,
  "merchantName": "Merchant D",
  "description": "Merchant D Description",
  "email": "mdemail@a.com",
  "active": false,
  "totalTransactionAmount": 0.0
}

###
# @name Activate Merchant
PATCH http://localhost:8080/merchant/2
Content-Type: application/json
Authorization: Basic merchant changeit
X-XSRF-TOKEN: ae9a0bda-5fe0-4d71-9a13-2d1b4fffc368

{ "ACTIVE": true }

###
# @name Get merchant
GET http://localhost:8080/merchant/2
Content-Type: application/json
Authorization: Basic merchant changeit


###
# @name Create Authorize tranzaction
POST http://localhost:8080/transaction
Content-Type: application/json
Authorization: Basic merchant changeit
X-XSRF-TOKEN: ae9a0bda-5fe0-4d71-9a13-2d1b4fffc368

{
  "amount": 100.34,
  "customerEmail": "eml@e.com",
  "customerPhone": "1234567890",
  "merchant": {
    "id": 1
  },
  "transactionStatus": "APPROVED",
  "transactionType": "AUTHORISE"
}

